// widget/src/widget-styles.ts

export const styles = {
  container: {
    display: "flex",
    flexDirection: "row" as const,
    width: "100%",
    height: "600px",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "14px",
    color: "#171717",
    backgroundColor: "#fafafa",
    borderRadius: "12px",
    overflow: "hidden",
    border: "1px solid #e5e5e5",
  },
  viewport: {
    flex: "1 1 60%",
    position: "relative" as const,
    backgroundColor: "#f5f5f5",
    minHeight: "300px",
  },
  panel: {
    flex: "1 1 40%",
    overflowY: "auto" as const,
    padding: "24px",
    borderLeft: "1px solid #e5e5e5",
    backgroundColor: "#ffffff",
  },
  optionGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontSize: "12px",
    fontWeight: "600" as const,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: "#737373",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #d4d4d4",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box" as const,
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #d4d4d4",
    fontSize: "14px",
    backgroundColor: "#ffffff",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  priceBar: {
    position: "sticky" as const,
    bottom: "0",
    padding: "16px 24px",
    borderTop: "1px solid #e5e5e5",
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  priceLabel: {
    fontSize: "10px",
    fontWeight: "600" as const,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    color: "#a3a3a3",
  },
  priceValue: {
    fontSize: "24px",
    fontWeight: "700" as const,
    color: "#171717",
  },
  button: {
    padding: "10px 20px",
    borderRadius: "8px",
    border: "none",
    fontSize: "14px",
    fontWeight: "600" as const,
    cursor: "pointer",
    transition: "background-color 0.2s",
    backgroundColor: "var(--widget-primary, #2563eb)",
    color: "#ffffff",
  },
  loading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "#a3a3a3",
  },
} as const;
